name: Create issues from a Python file.
on: [push]
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  
  python_create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Run the GitHub Rest API script
        working-directory: "src"
        run: python analysis.py
        # env: $ {{ secrets.GITHUB_TOKEN }}
